name: Build Android APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostcwd \
            kivy/buildozer \
            bash -c "cd /home/user/hostcwd && buildozer android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
